from pathlib import Path
import subprocess,html,json
P=Path(__file__).resolve().parent
OUT=P/'docs'
OUT.mkdir(parents=True,exist_ok=True)
pages=[('index','Start here'),('history','How the research developed'),('meetings','What has been agreed?'),('stock-structure','One stock or more?'),('data-surveys','Catches and surveys'),('assessments','How is the stock doing?'),('mse','Choosing management rules'),('sc14-week','This week at SC14'),('sources','Read the papers'),('contributing','Suggest an addition')]
css='''*{box-sizing:border-box}body{margin:0;background:#f3f6f8;color:#193649;font:17px/1.65 system-ui,sans-serif}header{background:#173f60;color:white;padding:22px 34px}header b{font-size:24px}header small{display:block;color:#dbe8ed}.layout{display:grid;grid-template-columns:255px minmax(0,1fr);max-width:1450px;margin:auto}nav{padding:24px 16px;position:sticky;top:0;height:100vh}nav a{display:block;color:#23495e;padding:8px 12px;text-decoration:none;border-radius:6px;font-size:15px}nav a.active{background:#dcece9;border-left:4px solid #007d78;font-weight:700}main{margin:25px 24px;padding:30px 42px;background:white;border-radius:12px;min-width:0}h1{font-size:34px;line-height:1.2;color:#173f60}details{margin:18px 0;padding:12px 16px;background:#f2f7f7;border-left:3px solid #007d78}summary{cursor:pointer;font-weight:650}h2{font-size:24px;margin-top:34px;color:#00746f}a{color:#005e83}table{border-collapse:collapse;font-size:14px;width:100%;margin:20px 0}th{background:#173f60;color:white;text-align:left}th,td{padding:12px;border:1px solid #dce4e9;vertical-align:top}tr:nth-child(even){background:#f5f8fa}.table-scroll{overflow-x:auto}footer{margin-top:36px;padding-top:18px;border-top:1px solid #dce4e9;font-size:14px;color:#516877}.banner{padding:12px 16px;background:#fff3dc;border-left:4px solid #ad6b19;margin-bottom:22px;font-size:14px}.skip{position:absolute;left:-9999px}.skip:focus{left:15px;background:white;z-index:2}.steps{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}.steps a{flex:1;padding:16px;background:#e8f2f0;border-bottom:4px solid #007d78;text-decoration:none;min-width:160px}.steps span{display:block;font-size:13px;color:#496172}@media(max-width:850px){.layout{display:block}nav{height:auto;position:static;display:flex;flex-wrap:wrap;padding:10px}main{margin:10px;padding:22px}h1{font-size:28px}th,td{min-width:120px}header{padding:18px}}@media print{nav,.banner,.skip{display:none}.layout{display:block}main{margin:0;padding:0}header{background:white;color:#173f60}header small{color:#173f60}}'''
(OUT/'style.css').write_text(css)
for slug,title in pages:
 source=P/'content'/f'{slug}.md'
 body=subprocess.check_output(['quarto','pandoc',str(source),'-f','gfm','-t','html5'],text=True)
 body=body.replace('<table>','<div class="table-scroll"><table>').replace('</table>','</table></div>')
 flow=''
 nav=''.join(f'<a href="{s}.html" class="{"active" if slug==s else ""}"'+(' aria-current="page"' if slug==s else '')+f'>{html.escape(t)}</a>' for s,t in pages)
 (OUT/f'{slug}.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} | Jack mackerel working wiki</title><link rel="stylesheet" href="style.css"></head><body><a class="skip" href="#main">Skip to content</a><header><b>Jack mackerel research</b><small>Research guide for fisheries managers · Information assembled 7 September 2026</small></header><div class="layout"><nav aria-label="Wiki pages">{nav}</nav><main id="main"><div class="banner">Research findings, proposals and agreed decisions are distinguished throughout this guide.</div>{flow}{body}<footer>Public working synthesis of the cited research · <a href="sources.html">Read the sources</a> · <a href="contributing.html">Suggest an addition</a> · <a href="https://github.com/SPRFMO/SC14_JM/blob/main/content/{slug}.md">Page source</a></footer></main></div></body></html>''')
print('Built',len(pages),'HTML pages')
